### ISSUE TITLE
Error in instantiation of configurations 

### ISSUE THREAD

**Issue by Speshals** [jjpFin/DHT22-TemperatureLogger#6]
Fresh install on RPI, Raspbian. 

`02-08-20 05:22:34 INFO root DHT22logger execution started
02-08-20 05:22:34 INFO Configurations.ConfigHandler ConfigHandler instantiation started
02-08-20 05:22:34 INFO Configurations.ConfigHandler Instantiate ConfigReader
02-08-20 05:22:34 INFO Configurations.ConfigReader ConfigReader instantiation started
02-08-20 05:22:34 INFO Configurations.ConfigReader Loading configurations from config.json
02-08-20 05:22:34 ERROR Configurations.ConfigHandler Instantiation failed
02-08-20 05:22:34 ERROR root Failed to get configurations:
Traceback (most recent call last):
  File "DHT22logger.py", line 58, in main
    configurationHandler = ConfigHandler()
  File "/home/pi/DHT22-TemperatureLogger/Configurations/ConfigHandler.py", line 17, in __init__
    self.configReader = ConfigReader()
  File "/home/pi/DHT22-TemperatureLogger/Configurations/ConfigReader.py", line 20, in __init__
    self.configurations = json.loads(open(configurationFile).read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by Speshals** [comment]
Fixed. I had commented out the 2nd sensor line in the example.
